name: Process PR Review Diff Comments

on:
  pull_request_review_comment:
    types: [created]

jobs:
  process-comment:
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print comment details
        run: |
          echo "Comment on file: ${{ github.event.comment.path }}"
          echo "Diff Hunk: ${{ github.event.comment.diff_hunk }}"
          echo "Comment text: ${{ github.event.comment.body }}"
          echo "Comment start line: ${{ github.event.comment.start_line }}"
          echo "Comment line: ${{ github.event.comment.line }}"

      - name: Add PR review comment with suggestion
        uses: sfontaneldatadome/add-pr-review-comment@multiline2

        with:
          # Dynamically construct the message with a suggestion on the commented lines
          comments: |
            [
              {
                "path": "${{ github.event.comment.path }}",
                "start_line": ${{ github.event.comment.start_line || github.event.comment.line }},
                "line": ${{ github.event.comment.line }},
                "text": "```suggestion\nthis is my new suggestion\n```",
                "side": "RIGHT"
              }
            ]
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'  # The user.login for temporary GitHub tokens
          allow-repeats: false
